- name: Install Postgres
  package:
    name : "{{ item }}"
    state : "present"
  with_items:
    - postgresql
    - postgresql-server

#- name: Initalize the database
 # shell: postgresql-setup initdb


- name: start and enable postgres service
  service:
    name: postgresql
    state: started
    enabled: yes


