- name: Install Postgres
  package:
    name : "{{ item }}"
    state : "present"
  with_items:
    - postgresql
    - postgresql-server
    - python-psycopg2

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initalize the database
  shell: postgresql-setup initdb
  when: not postgres_data.stat.exists

- name: start and enable postgres service
  service:
    name: postgresql
    state: started
    enabled: yes


